version: '3'
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=localBucketId
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=secretpassword
    command: sh -c "/init-influxdb.sh && exec influxd"

  chronograf:
    image: "chronograf:latest"
    ports:
      - "8888:8888"
    command: sh -c "/entrypoint.sh --influxdb-url=http://influxdb:8086"

