url: "http://localhost:8086"
bucketId: "localBucketId"
measurement: "measurement"
interval: "10s" # reporting interval
alignTimestamps: true # round timestamps to interval

# Required only for InfluxDB Cloud
#token: "access token"
#organizationId: "organizationId"
